name: CICD

on:
  workflow_dispatch:

jobs:
  static-analyze:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PWD (1)
        run: pwd

  sonarqube:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PWD (2)
        run: pwd

      - name: Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"ems_be" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build ./src/EMS_BE.sln
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  trivy-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PWD (3)
        run: pwd

      - name: List
        run: ls -a

      - name: Run Trivy
        run: trivy fs ./src > trivy-fs.txt

      - name: Upload Trivy result
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs.txt
          path: trivy-fs.txt
          if-no-files-found: error
