name: CICD

on:
  workflow_dispatch:

jobs:
  static-analyze:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  sonarqube:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"${{ vars.SONARQUBE_PROJECT_NAME }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build ./src/EMS_BE.sln
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  trivy-source-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy (file scan)
        run: trivy fs ./src > trivy-fs.txt

      - name: Upload Trivy result
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs.txt
          path: trivy-fs.txt
          if-no-files-found: error

  build-and-push-image:
    runs-on: self-hosted
    needs: [sonarqube, trivy-source-scan]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.IMAGE_NAME }}:latest
          context: ./src

  trivy-image-scan:
    runs-on: self-hosted
    needs: build-and-push-image

    steps:
      - name: Run Trivy (image scan)
        run: trivy image ${{ vars.IMAGE_NAME }}:latest > trivy-img.txt

      - name: Upload Trivy result
        uses: actions/upload-artifact@v4
        with:
          name: trivy-img.txt
          path: trivy-img.txt
          if-no-files-found: error
