name: CICD

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ems-api 

jobs:
  static-analyze:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  sonarqube:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"ems_be" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build ./src/EMS_BE.sln
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  trivy-source-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy
        run: trivy fs ./src > trivy-fs.txt

      - name: Upload Trivy result
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs.txt
          path: trivy-fs.txt
          if-no-files-found: error

  build-image:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t $IMAGE_NAME ./src

  trivy-image-scan:
    runs-on: self-hosted

    steps:
      - name: Run Trivy
        run: trivy image $IMAGE_NAME:latest
