name: CICD

on:
  # pull_request:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube scan
        run: |
          dotnet-sonarscanner begin /k:"${{ vars.SONARQUBE_PROJECT_NAME }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build ./src/EMS_BE.sln
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Trivy dependency scan
        run: trivy fs ./src > trivy-fs.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.IMAGE_NAME }}:latest
          context: ./src

      - name: Trivy image scan
        run: trivy image ${{ vars.IMAGE_NAME }}:latest > trivy-img.txt

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scans
          path: |
            trivy-fs.txt
            trivy-img.txt
          if-no-files-found: error

  cd:
    runs-on: self-hosted
    needs: [ci]
    environment: dev

    steps:
      - name: Deploy
        run: echo "Deploying..."
